#include "mainwindow.h"

#include <QApplication>

QString getStyleSheet();

int main(int argc, char *argv[])
{
    QApplication a(argc, argv);
    MainWindow w;
    w.show();

    a.setStyleSheet(getStyleSheet());
    return a.exec();
}

QString getStyleSheet()
{


    QString stylesheet =     "QWidget{"
                             "  background-color: #242425;"
                             "  color: #f1f1f1;"
                             "}"
                             ""
                             "QPushButton#btnDefault {"
                             "  padding: 6px 12px;"
                             "  margin-bottom: 0;"
                             "  font-size: 14px;"
                             "  color: #f1f1f1;"
                             "  background-color: #333333;"
                             "  border: 1px solid #888888;"
                             "  border-radius: 4px;"
                             "}"
                             ""
                             "QPushButton#btnDefault:hover {"
                             "  color: #f1f1f1;"
                             "  background-color: #242425;"
                             "  border: 1px solid #888888;"
                             "}"
                             ""
                             "QPushButton#btnDefault:pressed {"
                             "border: 3px solid #242425;"
                             "}"
                             ""
                             "QPushButton#btnDefault:disabled {"
                             "  color : #e1e1e1;"
                             "  background-color: #242425;"
                             "  border: 1px solid #242425;"
                             "}"
                             ""
                             "QPushButton#btnDefault:checked {"
                             "  color : #fff;"
                             "  background-color: #5A8E8E;"
                             "  border: 1px solid #888888;"
                             "}"
                             ""
                             "QLineEdit{"
                             "  color : #e1e1e1;"
                             "  background: #515153;"
                             "  border: 1px solid #888888;"
                             "  border-radius: 4px;"
                             "  padding: 6px 12px;"
                             "  margin-bottom: 0;"
                             "  selection-background-color: #5A8E8E;"
                             "}"
                             ""
                             "QLineEdit[readOnly=\"true\"]{"
                             "  color : #d1d1d1;"
                             "  background-color: #383838;"
                             "  border: 1px solid #444444;"
                             "  border-radius: 4px;"
                             "  padding: 6px 12px;"
                             "  margin-bottom: 0;"
                             "}"
                            ""
                            "QComboBox {"
                            "  color : #e1e1e1;"
                            "  background-color: #515153;"
                            "    border: 1px solid #888888;"
                            "  border-radius: 4px;"
                            "  padding: 6px 12px;"
                            "  min-width: 6em;"
                            "}"
                            ""
                            "QComboBox:editable {"
                            "    background-color: #333333;"
                            "}"
                            ""
                            "QComboBox:!editable, QComboBox::drop-down:editable {"
                            "     background-color: #515153;"
                            "}"
                            ""
                            "QComboBox:!editable:on, QComboBox::drop-down:editable:on {"
                            "    background-color: #242425;"
                            "}"
                            ""
                            "QComboBox:on { "
                            "    padding-top: 3px;"
                            "    padding-left: 4px;"
                            "}"
                            ""
                            "QComboBox::drop-down {"
                            "  subcontrol-origin: padding;"
                            "  subcontrol-position: top right;"
                            "  width: 15px;"
                            ""
                            "  border-left-width: 1px;"
                            "  border-left-color: darkgray;"
                            "  border-top-right-radius: 4px;"
                            "  border-bottom-right-radius: 4px;"
                            "}"
                            ""
                            "QComboBox::down-arrow {"
                            "    image: url(angle-arrow-down.svg);"
                            "    width: 10px;"
                            "    height: 10px;"
                            "    padding-right: 4px;"
                            "}"
                            ""
                            "QComboBox::down-arrow:on { "
                            "    top: 1px;"
                            "    left: 1px;"
                            "}"
                            ""
                            "QComboBox QAbstractItemView {"
                            "  background-color: #333333;"
                            "  border: none;"
                            "  selection-background-color: #242425;"
                            "    color: #e1e1e1;"
                            "    selection-color: #e1e1e1;"
                            "}"
                            ""
                            "QMessageBox {"
                            "  background-color: #333333;"
                            "}"
                            ""
                            "QMessageBox QLabel {"
                            "  color: #aaa;"
                            "}"
                            ""
                            "QMessageBox QPushButton {"
                            "  padding: 6px 12px;"
                            "  margin-bottom: 0;"
                            "  font-size: 14px;"
                            "  color: #fff;"
                            "  background-color: #5A8E8E;"
                            "  border: 1px solid #5A8E8E;"
                            "  border-radius: 4px;"
                            "}"
                            "QProgressBar {"
                            "    border: 1px solid #888888;"
                            "    border-radius: 7px;"
                            "    text-align: center;"
                            "    color: #d1d1d1;"
                            "    height: 6px;"
                            "    background-color: #515153;"
                            "}"
                            ""
                            "QProgressBar::chunk {"
                            "    background-color: #5A8E8E;"
                            "    border-radius: 7px;"
                            "}"
                            ""
                             "QTextEdit{"
                             " color: #e1e1e1;"
                             " background-color: #333333;"
                             " selection-color: #f1f1f1; "
                             " selection-background-color: #404040; "
                             " border: 1px solid #242424;"
                             "}";
    return stylesheet;

}
